import { Link } from 'react-router-dom'
import LegalLayout from './LegalLayout'

export default function Terms() {
  return (
    <LegalLayout title="Terms and Conditions" updated="14 July 2026">
      <p>
        These Terms and Conditions ("Terms") govern your use of MatchPulse, a
        multi-sport tournament management and live scoring platform accessible
        through our website and web application (the "Platform"). MatchPulse
        is operated by the entity referred to in these Terms as "MatchPulse",
        "we", "us" or "our".
      </p>
      <p>
        By creating an account, purchasing a plan, or otherwise using the
        Platform, you agree to these Terms. If you do not agree, do not use
        the Platform.
      </p>

      <h2>1. Definitions</h2>
      <p><strong>Organiser</strong> means a person or organisation that creates or administers a competition, tournament, league or match on the Platform.</p>
      <p><strong>Player</strong> means an individual whose participation, profile or statistics are recorded on the Platform.</p>
      <p><strong>Manager</strong> means a person who administers a team or a group of Players.</p>
      <p><strong>Parent</strong> means a parent or legal guardian of a Player who is a minor.</p>
      <p><strong>Spectator</strong> means a person who uses the Platform to view competitions, results or statistics.</p>
      <p><strong>User</strong> means any person who uses the Platform, including Organisers, Players, Managers, Parents and Spectators.</p>
      <p><strong>Paid Plan</strong> means any paid plan we offer, as described on our pricing page. Some Paid Plans are once-off and some run for a fixed period.</p>
      <p><strong>Content</strong> means any data, text, results, scores, images, team information, player information and other material submitted to or generated on the Platform.</p>

      <h2>2. Accounts</h2>
      <p>2.1. You may need an account to use certain features. You are responsible for the accuracy of the information you provide and for keeping your login details secure.</p>
      <p>2.2. You are responsible for all activity that happens under your account. Tell us promptly if you believe your account has been accessed without your permission.</p>
      <p>2.3. You must be old enough to enter into a binding agreement under South African law to hold an account in your own name. If you are a minor, a Parent must consent to and manage your account, as set out in clause 6.</p>
      <p>2.4. We may suspend or close an account that breaches these Terms, our Acceptable Use Policy, or applicable law.</p>

      <h2>3. Roles and responsibilities</h2>
      <p>3.1. <strong>Organisers</strong> are responsible for the competitions they run on the Platform, including matches, results, and the accuracy of the information they publish. Organisers confirm the outcome of every match through the Platform's manual confirmation process.</p>
      <p>3.2. <strong>Organisers cannot create Player profiles</strong> and cannot attach a Player's name to live scoring in a competition. Only a Player, a Parent, or a Manager may create and manage a Player profile. This is a deliberate design choice, and it means the person who creates a profile is responsible for that profile and for any consent required to publish it.</p>
      <p>3.3. <strong>Players, Parents and Managers</strong> who create profiles are responsible for the information in those profiles and confirm they are entitled to publish it. Where a profile relates to a minor, clause 6 applies.</p>
      <p>3.4. <strong>Spectators</strong> may view public competition information subject to these Terms.</p>

      <h2>4. Content and ownership</h2>
      <p>4.1. You keep ownership of the Content you submit. By submitting Content, you grant us a licence to host, display, process and distribute it for the purpose of operating the Platform, including showing competition results and statistics on public pages.</p>
      <p>4.2. You are responsible for the Content you submit and confirm you have the right to submit it.</p>
      <p>4.3. We may remove Content that breaches these Terms, our Acceptable Use Policy, or the law, or that we are required to remove following a valid request under clause 6 or our Privacy Policy.</p>
      <p>4.4. Competition results, standings and statistics generated by the Platform's stats engine are provided for general information. We take reasonable care to calculate them correctly, but Organisers are responsible for confirming match outcomes, and we do not warrant that every figure is free of error.</p>

      <h2>5. Plans, pricing and payment</h2>
      <p>5.1. We offer a free plan and one or more Paid Plans. The plans available at any time, what each one includes, and their prices are set out on our <Link to="/products">pricing page</Link>. Prices are in South African Rand and include VAT where applicable.</p>
      <p>5.2. We may change our plans and pricing. Any change applies to new purchases and to renewals that fall due after the change takes effect. The pricing page always reflects the current position.</p>
      <p>5.3. Payments are processed by PayFast. By purchasing a Paid Plan, you also agree to PayFast's terms. We do not store your full card details.</p>
      <p>5.4. The pricing principle is simple: you pay for what you host, not for what you play in. Participating in a competition someone else hosts does not require a Paid Plan.</p>

      <h3>Renewals</h3>
      <p>5.5. Some Paid Plans are once-off. Others run for a fixed period — for example, a year — and then end. Plans do not renew automatically, and you are not charged again unless you make a new purchase. To continue after a plan ends, you buy it again. Whether a plan is once-off or for a fixed period, and its expiry date, are shown at the time of purchase, on your account page, and on our pricing page.</p>
      <p>5.6. We do not currently send a reminder before a plan ends, so please check the expiry date on your account page if you want to buy again before it lapses. When a Paid Plan ends, your existing competitions, results and data are not deleted — you simply cannot create new competitions under that plan until you buy again.</p>

      <h3>Refunds</h3>
      <p>5.7. You may request a refund of a Paid Plan <strong>before a competition has begun or holds active data</strong> under that plan. Once a competition tied to the plan has started or contains active match data, the plan is treated as used and <strong>no refund is payable</strong>. This applies to both once-off and fixed-period plans.</p>
      <p>5.8. Clause 5.7 sets out your rights under this policy. It does not limit any right you have under the Consumer Protection Act or the Electronic Communications and Transactions Act that cannot be excluded by agreement.</p>

      <h2>6. Minors</h2>
      <p>6.1. The Platform may record the names and statistics of Players who are minors, for example in schools and junior sport.</p>
      <p>6.2. A Player profile relating to a minor may only be created and managed by the Player's Parent, or by a Manager acting with the Parent's consent. Whoever creates the profile confirms that they have the authority and any consent required to publish the minor's information.</p>
      <p>6.3. A Parent may ask us to correct or remove a minor's information at any time. Requests are handled as described in our <Link to="/legal/privacy">Privacy Policy</Link>.</p>

      <h2>7. Acceptable use</h2>
      <p>Your use of the Platform is subject to our <Link to="/legal/acceptable-use">Acceptable Use Policy</Link>, which forms part of these Terms.</p>

      <h2>8. Availability and changes</h2>
      <p>8.1. We aim to keep the Platform available and working well, but we do not guarantee uninterrupted access. We may carry out maintenance, updates and changes, and we may add, change or remove features.</p>
      <p>8.2. We may change these Terms. If we make a material change, we will take reasonable steps to let you know. Continuing to use the Platform after a change means you accept the updated Terms.</p>

      <h2>9. Liability</h2>
      <p>9.1. To the extent permitted by law, the Platform is provided "as is". We do not give warranties beyond those we cannot lawfully exclude.</p>
      <p>9.2. To the extent permitted by law, we are not liable for indirect or consequential loss, or for loss arising from Content submitted by Users, from decisions made based on results or statistics, or from matters outside our reasonable control.</p>
      <p>9.3. Nothing in these Terms limits liability that cannot be limited by law, including liability for death or personal injury caused by our negligence, or for fraud.</p>

      <h2>10. Suspension and termination</h2>
      <p>10.1. You may stop using the Platform at any time. Where you hold a Paid Plan, clause 5 governs renewals and refunds.</p>
      <p>10.2. We may suspend or end your access if you breach these Terms, our Acceptable Use Policy, or the law, or where we are required to by law.</p>

      <h2>11. General</h2>
      <p>11.1. These Terms are governed by the laws of the Republic of South Africa, and the South African courts have jurisdiction.</p>
      <p>11.2. If any part of these Terms is found to be unenforceable, the rest remains in force.</p>
      <p>11.3. These Terms, together with the <Link to="/legal/privacy">Privacy Policy</Link>, <Link to="/legal/cookies">Cookie Policy</Link> and <Link to="/legal/acceptable-use">Acceptable Use Policy</Link>, are the whole agreement between you and us regarding the Platform.</p>

      <h2>12. Contact</h2>
      <p>For any question about these Terms, please use our <Link to="/#contact">contact form</Link>.</p>
    </LegalLayout>
  )
}
